# Load required packages
library(shiny)
library(shinyjs)
library(dplyr)
library(DT)
library(igraph)
library(RColorBrewer)
library(grDevices)
library(ggplot2)
library(fields) # # Required for image.plot function # install.packages("fields")

# Define UI for the application
ui <- fluidPage(
  useShinyjs(),  # Enable shinyjs for additional JavaScript functionalities
  titlePanel("scROAD - Single-cell Regulatory Occupancy Archive in Dementia"),
  
  tabsetPanel(
    tabPanel("Home",
             fluidPage(
               titlePanel("Welcome to the Single-cell Regulatory Occupancy Archive in Dementia"),
               
               # First row with the BioSciIcon
               fluidRow(
                 column(12, img(src = "https://www.bio.uci.edu/wp-content/uploads/2024/04/uci-charlie-dunlop-dark-blue-logo-with-gradient-dna_optimized.png", height = "50px", style="display: block; margin-left: 0;"))
               ),
               
               # Second row with the other three logos
               fluidRow(
                 column(4, img(src = "https://raw.githubusercontent.com/rootze/rootze.github.io/master/assets/img/swaruplab.png", height = "100px", style="display: block; margin-left: auto; margin-right: auto;")),
                 column(4, img(src = "https://raw.githubusercontent.com/rootze/scCis-TF/main/images/logo_database.png", height = "100px", style="display: block; margin-left: auto; margin-right: auto;")),
                 column(4, img(src = "https://raw.githubusercontent.com/rootze/scCis-TF/main/images/logo.png", height = "100px", style="display: block; margin-left: auto; margin-right: auto;"))
               ),
               hr(),
               h3("What We Can Do with scATAC-seq Data"),
               p("scATAC-seq data enables us to explore chromatin accessibility at a single-cell level, allowing for the identification of regulatory elements that are active in specific cell types. This technique is particularly powerful for investigating transcription factor binding sites (TFBS) and understanding gene regulatory networks in the context of complex diseases like Alzheimer's Disease (AD) and Pick's Disease (PiD)."),
               p("Our comprehensive approach integrates genomic data from various sources, including GWAS fine-mapping, single-nucleus ATAC-seq (snATAC-seq), and single-nucleus RNA-seq (snRNA-seq), to uncover the genetic underpinnings of neurodegenerative diseases. By mapping disease-associated loci to specific cell types, we can investigate the functional alternations due to genetic variants in disease contexts, such as AD and PiD."),
               p(HTML('I developed a wrapper package, <a href="https://github.com/rootze/scCis-TF" target="_blank">scCis-TF</a>, designed to streamline the extracting information from single-cell data generated by CellRanger ATAC, Seurat, and Signac into Cicero and TOBIAS for comprehensive analysis. We performed single cell co-accessibility analyses using <a href="https://cole-trapnell-lab.github.io/cicero-release/docs_m3/" target="_blank">Cicero</a> to construct putative cis-regulatory enhancer-promoter links. Additionally, with the help from <a href="https://github.com/loosolab/TOBIAS" target="_blank">TOBIAS</a> package, we can further explore transcription factor (TF) binding occupancy in ATAC-seq. This analysis allows us to detect differences in TF binding between disease and control samples, providing insights into how regulatory mechanisms are altered in specific cell types. By integrating TF binding data with co-accessibility analyses to create this scCis-TF interactive database, users can easily explore transcription factor binding activity and their implications in disease, providing a valuable resource for understanding gene regulation in neurodegeneration.')),
               img(src = "https://raw.githubusercontent.com/rootze/scCis-TF/main/images/GWAS_snATAC_scCis-TF.png", height = "800px"),
               hr(),
               h3("About the Database"),
               p("This database offers comprehensive information on single-cell cCRE transcription factor occupancy data generated from snATAC-seq analysis of human postmortem prefrontal cortex (PFC) tissue. The data specifically focuses on Alzheimer's Disease and Pick's Disease. For a more in-depth understanding of the database's purpose and contents, please refer to the following publication. If you have any further questions, feel free to contact the principal investigator."),
               hr(),
               h3("How to Cite"),
               p("Shi, Das & Morabito et al. Single-nucleus multi-omics identifies shared and distinct pathways in Pick’s and Alzheimer’s disease."),
               hr(),
               h3("Principal Investigator"),
               p("Name: Vivek Swarup"),
               p(HTML('Lab Website: <a href="https://swaruplab.bio.uci.edu/" target="_blank">https://swaruplab.bio.uci.edu/</a>')),
               hr(),
               h3("Developer Information"),
               p("Name: Zechuan Shi"),
               p(HTML('GitHub: <a href="https://rootze.github.io/" target="_blank">rootze.github.io</a>'))
             )
    ),
    
    tabPanel("Introductory Vignettes",
             fluidPage(
               tags$style(HTML("
            ol li {
                margin-bottom: 10px; /* Adds space between the main steps */
            }
            ul li {
                margin-bottom: 0px; /* Adds space between the subtext items */
            }
        ")),
               h3("Explanation of TF Occupancy Data Frame Columns"),
               p("Below is an explanation of the columns included in the TF Occupancy data frame:"),
               tags$ul(
                 tags$li("Peak1: Peak1 open chromatin regions (OCRs)"),
                 tags$li("Peak1_nearestGene: Nearest gene to Promoter Peak1"),
                 tags$li("Peak1_type: Promoter - Peak Type of Peak1, and this is set by us to be promoter for easy investigation of links from Peak2 OCRs to Peak1 Promoter"),
                 tags$li("Peak2: Peak2 open chromatin regions"),
                 tags$li("Peak2_type: Peak Types of Peak2 -- Enhancer, which includes Distal and Intronic, and Exonic OCRs"),
                 tags$li("chr: Chromosome"),
                 tags$li("delta_coaccess_dx_vs_cnt: Difference in coaccessibility between disease and control"),
                 tags$li("Celltype: Type of cell"),
                 tags$li("Study: Study from which the data is derived, AD or PiD"),
                 tags$li("TFBS_chr: Chromosome of the Transcription Factor Binding Sites (TFBSs)"),
                 tags$li("TFBS_start: Start position of the TFBS"),
                 tags$li("TFBS_end: End position of the TFBS"),
                 tags$li("TFBS_name: Name of the transcription factor binding site"),
                 tags$li("TFBS_strand: Strand of the TFBS"),
                 tags$li("target_peak_chr: Chromosome of the target peak for the investigation of TFBS occupancy"),
                 tags$li("target_peak_start: Start position of the target peak for the investigation of TFBS occupancy"),
                 tags$li("target_peak_end: End position of the target peak for the investigation of TFBS occupancy"),
                 tags$li("control_bound: Control TF binding information on the target peak, 1 means [bound / binding], 0 means [no bound / no binding]"),
                 tags$li("dx_bound: Disease TF binding information on the target peak"),
                 tags$li("log2FC_TFBS: log2 fold-changes estimated from TOBIAS activity scores on the target peak, calculated by comparsing the change between Disease and Control")
               ),
               hr(),
               h3("Tutorial for TF Occupancy Data Explorer"),
               p("Follow these steps to use the TF Occupancy Data Explorer:"),
               tags$ol(
                 tags$li(
                   strong("Step 1: Decide Your Search Criteria"),
                   tags$p("Determine Your Focus: Decide whether you want to search for data based on a Target Gene, Transcription Factor (TF), Chromosome Base Position, or a combination of these."),
                   tags$ul(
                     tags$li(strong("Target Gene:"), " If you are interested in exploring transcription factor occupancy related to a specific gene."),
                     tags$li(strong("Transcription Factor:"), " If your focus is on how a particular TF interacts across different regions or genes."),
                     tags$li(strong("Chromosome Base Position:"), " If you have a specific genomic location of interest (e.g., from an SNP).")
                   )
                 ),
                 tags$li(
                   strong("Step 2: Enter Your Search Parameters in the TF Occupancy Database"),
                   tags$p("Access the TF Occupancy Database: Navigate to the single-cell cCRE Transcription Factor Occupancy Database in Dementia Research."),
                   tags$ul(
                     tags$li(strong("Option 1 - Target Gene Search:")),
                     tags$ul(
                       tags$li("Enter Target Gene Name: In the 'Target Selection' section, input the name of the gene you’re interested in."),
                       tags$li("(Optional) Enter TF Name: If you want to narrow down the search to a specific TF interacting with this gene, enter the TF name.")
                     ),
                     tags$li(strong("Option 2 - Transcription Factor Search:")),
                     tags$ul(
                       tags$li("Enter Transcription Factor Name: In the 'Target Selection' section, input the name of the TF to explore its occupancy across different genomic regions."),
                       tags$li("(Optional) Enter Target Gene Name: If you want to focus on a particular gene that interacts with this TF, enter the gene name.")
                     ),
                     tags$li(strong("Option 3 - Chromosome Base Position Search (Optional):")),
                     tags$ul(
                       tags$li("Enter Chromosome Base Position: If you also have a specific chromosome base position, input it in the 'Chr Base Position Search' section."),
                       tags$li("Set Window Size: Define the search window size (e.g., 1000 bp) around the base position to refine the region of interest."),
                       tags$li("Select Search Type, Target Gene OCR or TFBS, for the Base Position Search.")
                     )
                   )
                 ),
                 tags$li(
                   strong("Step 3: Load Data and View Results"),
                   tags$p("Load Data: Click on the 'Load Data' button to retrieve data based on the criteria you entered."),
                   tags$p("View Results: The database will display relevant entries, including peak information, transcription factor binding, cell type, and more."),
                   tags$p("Download Data and Plots: You can download the data and transcription factor plots by using the available buttons.")
                 ),
                 tags$li(
                   strong("Step 4: Analyze the Results"),
                   tags$p("Inspect TF Plots: Review the TF-Gene Regulatory Network plots generated from the data to visualize interactions between transcription factors and target genes."),
                   tags$p("Use Data for Further Analysis: Utilize the downloaded data for deeper analysis, such as studying transcription factor occupancy patterns in different cell types or diseases.")
                 )
               ),
               img(src = "https://raw.githubusercontent.com/rootze/scCis-TF/main/images/scCis-TF_IntroductoryVignettes.png", height = "800px", style="display: block; margin-left: auto; margin-right: auto;")
             )
    ),
    
    tabPanel("TF Occupancy Data Explorer",
             sidebarLayout(
               sidebarPanel(
                 tags$p(style = "color: red;", "Note for researchers: Due to the enormous size of the data for the TF binding prediction on the cis-regulatory OCRs for targeted genes, please use target selection, Chr position search, or both to fine-tune your search further."),
                 selectInput("disease", "Select Disease", choices = c("Alzheimer's Disease vs Age-matched Control" = "AD", "Pick's Disease vs Age-matched Control" = "PiD")),
                 selectInput("cellType", "Select Cell Type for TF occupancy", choices = c("ASC", "EX", "INH", "ODC", "MG", "OPC", "PER.END")),
                 selectInput("peakType", "Select Peak Type for TF occupancy", choices = c("Enhancer", "Exonic", "Promoter")),
                 selectInput("chromosome", "Select Chromosome for Target Gene/TF locate on", choices = c(paste0("chr", 1:22), "chrX")),
                 
                 # Target Selection Section
                 tags$div(style = "background-color: #eae0bb; padding: 10px; border-radius: 5px; margin-top: 20px;",
                          h4("Target Selection"),
                          textInput("targetGene", "Enter Target Gene Name", value = ""),
                          textInput("tfName", "Enter Transcription Factor Name", value = "")
                 ),
                 
                 # Chr Position Section
                 tags$div(style = "background-color: #d2c1e2; padding: 10px; border-radius: 5px; margin-top: 20px;",
                          h4("Chr Base Position Search"),
                          p(HTML('<span style="font-size:11px;">This Base position search could be used for searching SNP/nucleotide base position, e.g.: rs9272480 - chr6:32638023 (GRCh38), you can enter Base Position 32638023, no need to put chr6, since it is selected above. You can find SNP position through <a href="https://www.ncbi.nlm.nih.gov/snp/" target="_blank">dbSNP-NCBI</a>. Please be aware that we performed our analyses based on the reference: Genome Reference Consortium Human Build 38 (GRCh38), so ensure that you search for human genome positions accordingly.</span>')),
                          numericInput("baseLocation", "Enter Base Position", value = NULL, min = 0),
                          numericInput("windowSize", "Enter Window Size (bp)", value = 1000, min = 0),
                          radioButtons("searchType", "Select Search Type for the Base Position Search", 
                                       choices = list("Target Gene OCR" = "target", "TFBS" = "tfbs"),
                                       selected = "target")
                 ),
                 
                 fluidRow(
                   column(6, actionButton("loadData", "Load Data")),
                   column(6, downloadButton("downloadData", "Download TFBS Data"))
                 ),
                 br(),
                 fluidRow(
                   column(6, actionButton("plotNetwork", "Plot TF Network")),
                   column(6, downloadButton("downloadPlot", "Download Network Plot"))
                 ),
                 br(),
                 uiOutput("progressUI"),
                 uiOutput("status")  # Changed to uiOutput to support HTML rendering
               ),
               
               mainPanel(
                 DTOutput("table"),
                 plotOutput("networkPlot")
               )
             )
    )
  )
)

# Define server logic
server <- function(input, output, session) {
  
  # Reactive values to track the state of data loading and plot generation
  values <- reactiveValues(data_loaded = FALSE, plot_generated = FALSE)
  
  # Function to load data based on inputs
  load_data <- function(disease, cell_type, peak_type, chromosome) {
    file_path <- file.path("/Users/zetristanshi/Desktop/TFBS_database/Shiny", disease, cell_type, peak_type, paste0(chromosome, "_TFBS_database.rda"))
    if (file.exists(file_path)) {
      withProgress(message = "Loading data...", value = 0, {
        incProgress(0.5)
        load(file_path)
        incProgress(1)
        return(chr_df) # assuming the loaded data is stored in a variable named `chr_df`
      })
    } else {
      return(NULL)
    }
  }
  
  # Reactive value to store the data
  data <- reactiveVal(NULL)
  
  # Observe the loadData button
  observeEvent(input$loadData, {
    # Clear the previous data from memory and reset flags
    data(NULL)
    values$data_loaded <- FALSE
    values$plot_generated <- FALSE
    
    output$progressUI <- renderUI({
      tagList(
        shiny::withProgress(message = 'Loading data...', value = 0, {
          Sys.sleep(0.5)  # Simulate some loading time
          incProgress(1)
        })
      )
    })
    
    loaded_data <- tryCatch({
      load_data(input$disease, input$cellType, input$peakType, input$chromosome)
    }, error = function(e) {
      output$status <- renderUI({
        tags$p(paste("Error loading data:", e$message, "Please contact the developer."),
               style = "color: red; font-weight: bold; font-size: 16px;")
      })
      NULL
    })
    
    # Update the reactive value and flags
    data(loaded_data)
    if (!is.null(loaded_data)) {
      values$data_loaded <- TRUE
    }
    
    # Update status message based on data loading
    output$status <- renderUI({
      if (is.null(loaded_data)) {
        tags$p("Failed to load data or data exceeds memory limits.", 
               style = "color: red; font-weight: bold; font-size: 16px;")
      } else if (nrow(loaded_data) == 0) {
        tags$p("Data loaded successfully but no results found.", 
               style = "color: orange; font-weight: bold; font-size: 16px;")
      } else {
        tags$p("Data loaded successfully.", 
               style = "color: green; font-weight: bold; font-size: 16px;")
      }
    })
  })
  
  # Reactive expression to filter data based on user input
  filtered_data <- reactive({
    req(values$data_loaded) # Ensure data is loaded before filtering
    df <- data()
    if (!is.null(df)) {
      if (input$targetGene != "") {
        df <- df %>% filter(grepl(input$targetGene, Peak1_nearestGene, ignore.case = TRUE))
      }
      if (input$tfName != "") {
        df <- df %>% filter(grepl(input$tfName, TFBS_name, ignore.case = TRUE))
      }
      half_window <- input$windowSize / 2
      if (!is.null(input$baseLocation) && !is.na(input$baseLocation) && half_window > 0) {
        if (input$searchType == "target") {
          df <- df %>% filter(target_peak_start <= (input$baseLocation + half_window) & target_peak_end >= (input$baseLocation - half_window))
        } else if (input$searchType == "tfbs") {
          df <- df %>% filter(TFBS_start <= (input$baseLocation + half_window) & TFBS_end >= (input$baseLocation - half_window))
        }
      }
    }
    df
  })
  
  # Output table
  output$table <- renderDT({
    req(filtered_data()) # Ensure data is available
    datatable(filtered_data(), options = list(scrollX = TRUE, scrollY = "500px"))
  })
  
  # Update status message based on filtering
  observe({
    if (!is.null(data()) && nrow(filtered_data()) == 0) {
      output$status <- renderUI({
        tags$p("Data loaded successfully but no results found.",
               style = "color: orange; font-weight: bold; font-size: 16px;")
      })
    }
  })
  
  # Disable download buttons initially
  observe({
    shinyjs::disable("downloadData")
    shinyjs::disable("downloadPlot")
  })
  
  # Enable the data download button if data is loaded
  observe({
    if (values$data_loaded) {
      shinyjs::enable("downloadData")
    }
  })
  
  # Enable the plot download button if the plot is generated
  observe({
    if (values$plot_generated) {
      shinyjs::enable("downloadPlot")
    }
  })
  
  # Show warning if attempting to download data without loading it
  observeEvent(input$downloadData, {
    if (!values$data_loaded) {
      showModal(modalDialog(
        title = "Warning",
        "Please load the data before attempting to download.",
        easyClose = TRUE,
        footer = NULL
      ))
    }
  })
  
  # Show warning if attempting to download plot without generating it
  observeEvent(input$downloadPlot, {
    if (!values$plot_generated) {
      showModal(modalDialog(
        title = "Warning",
        "Please generate the plot before attempting to download.",
        easyClose = TRUE,
        footer = NULL
      ))
    }
  })
  
  # Download filtered data as CSV with a progress indicator
  output$downloadData <- downloadHandler(
    filename = function() {
      paste("TFBS_data_", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      withProgress(message = 'Preparing download...', value = 0, {
        
        # Simulate some progress steps (you can adjust or remove these if not needed)
        incProgress(0.3, detail = "Filtering data...")
        Sys.sleep(0.5)  # Simulate time-consuming tasks
        
        incProgress(0.3, detail = "Writing CSV file...")
        Sys.sleep(0.5)  # Simulate more time-consuming tasks
        
        # Write the filtered data to the file
        write.csv(filtered_data(), file, row.names = FALSE)
        
        # Finalize progress
        incProgress(0.4, detail = "Finalizing...")
        Sys.sleep(0.5)  # Simulate final steps
        
      })
    }
  )
  
  
  # Observe the plotNetwork button and construct the network plot
  observeEvent(input$plotNetwork, {
    req(filtered_data())
    
    # Extract TFs and target genes
    tf_gene_pairs <- distinct(filtered_data(), TFBS_name, Peak1_nearestGene, .keep_all = TRUE) %>% 
      select(TFBS_name, Peak1_nearestGene, log2FC_TFBS)
    
    # Simplified importance logic: Use log2FC_TFBS as a gain-like metric
    tf_gene_pairs <- tf_gene_pairs %>% 
      rename(Gain = log2FC_TFBS) %>% 
      arrange(desc(abs(Gain)))
    
    # Keep top 20 pairs for visualization
    top_tf_gene_pairs <- tf_gene_pairs %>% 
      top_n(20, wt = abs(Gain))
    
    # Construct network
    graph_data <- graph_from_data_frame(top_tf_gene_pairs, directed = TRUE)
    
    # Define colors for the gradient
    edge_colors <- colorRampPalette(c("blue", "white", "orange"))(100)
    E(graph_data)$color <- edge_colors[cut(E(graph_data)$Gain, breaks = 100)]
    
    # Define shapes
    V(graph_data)$shape <- ifelse(V(graph_data)$name %in% top_tf_gene_pairs$TFBS_name, "square", "circle")
    
    # Define sizes and labels
    V(graph_data)$size <- 12
    V(graph_data)$label.cex <- 0.8
    V(graph_data)$label.family <- "sans"
    V(graph_data)$color <- ifelse(V(graph_data)$shape == "square", "yellow", "lightblue")
    
    # Set a seed for reproducibility
    set.seed(123)  # Replace 123 with your preferred seed number
    
    # Generate layout using layout_nicely for the network
    layout <- layout_nicely(graph_data)
    
    # Plot network with legend
    output$networkPlot <- renderPlot({
      par(mar = c(1, 1, 1, 7))  # Adjust margins to add space for the legend
      plot(graph_data, 
           layout = layout, 
           main = "TF-Gene Regulatory Network for Top 20 TF-Gene Pairs",
           vertex.label = V(graph_data)$name,
           vertex.label.color = "black",
           vertex.label.font = 2,
           vertex.label.cex = V(graph_data)$label.cex,
           vertex.color = V(graph_data)$color,
           edge.width = 2,
           vertex.shape = V(graph_data)$shape,
           edge.color = E(graph_data)$color)
      
      # Add legend for shapes, adjusting position
      legend("topleft",  # Adjust position to avoid overlap with the color scale
             legend = c("TF", "Gene"), 
             pch = c(15, 16),  # Correct shape symbols # "15 -- TF (Square)", "16 -- Gene (Circle)"
             col = c("yellow", "lightblue"), 
             pt.cex = 2,  # Increase point size in legend for visibility
             bty = "n", cex = 0.8)
      
      # Add color scale
      image.plot(legend.only = TRUE, zlim = c(-1, 1), col = edge_colors, 
                 legend.shrink = 0.5, smallplot = c(0.85, 0.88, 0.2, 0.8),
                 legend.args = list(text = "log2FC TFBS DX vs Cont", side = 2, font = 2, line = 1))
    }, res = 150)
    
    # Update plot generation flag
    values$plot_generated <- TRUE
    
    # Save the plot as a PDF file
    output$downloadPlot <- downloadHandler(
      filename = function() {
        paste("TF_Gene_Network_", Sys.Date(), ".pdf", sep = "")
      },
      content = function(file) {
        pdf(file, width = 10, height = 10)  # Reduce size for better fit
        par(mar = c(1, 1, 1, 7))  # Adjust margins to add space for the legend
        plot(graph_data, 
             layout = layout,  # Use the same layout for reproducibility
             main = "TF-Gene Regulatory Network",
             vertex.label = V(graph_data)$name,
             vertex.label.color = "black",
             vertex.label.font = 2,
             vertex.label.cex = V(graph_data)$label.cex,
             vertex.color = V(graph_data)$color,
             edge.width = 2,
             vertex.shape = V(graph_data)$shape,
             edge.color = E(graph_data)$color)
        
        # Add legend for shapes, adjusting position
        legend("topleft",  # Adjust position to avoid overlap with the color scale
               legend = c("TF", "Gene"), 
               pch = c(15, 16),  # Correct shape symbols
               col = c("yellow", "lightblue"), 
               pt.cex = 2,  # Increase point size in legend for visibility
               bty = "n", cex = 0.8)
        
        # Add color scale
        image.plot(legend.only = TRUE, zlim = c(-1, 1), col = edge_colors, 
                   legend.shrink = 0.5, smallplot = c(0.85, 0.88, 0.2, 0.8),
                   legend.args = list(text = "log2FC TFBS DX vs Cont", side = 2, font = 2, line = 1))
        dev.off()
      }
    )
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
